name: "CICD"

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  Linter:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Perform static code analysis via golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.5